-- =====================================================
-- SLIDES TABLE MIGRATION FOR AI SLIDE GENERATION
-- Purpose: Ensure slides table accommodates complete AI slide generation system
-- Date: 2025-11-03
-- =====================================================

-- Step 1: Check if slides table exists and add missing columns if needed
-- This migration is idempotent and safe to run multiple times

BEGIN;

-- Add missing columns if they don't exist (PostgreSQL 9.6+)
-- Using IF NOT EXISTS for safety

ALTER TABLE slides
ADD COLUMN IF NOT EXISTS slide_type TEXT DEFAULT 'content' CHECK (slide_type IN ('intro', 'content', 'conclusion'));

ALTER TABLE slides
ADD COLUMN IF NOT EXISTS is_edited BOOLEAN DEFAULT FALSE;

ALTER TABLE slides
ADD COLUMN IF NOT EXISTS edit_notes TEXT;

ALTER TABLE slides
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;

ALTER TABLE slides
ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES profiles(id) ON DELETE SET NULL;

-- Ensure existing columns have correct types and constraints
-- Update NOT NULL constraints where needed
ALTER TABLE slides
ALTER COLUMN title SET NOT NULL;

ALTER TABLE slides
ALTER COLUMN content SET NOT NULL;

ALTER TABLE slides
ALTER COLUMN narration DROP NOT NULL;

-- Add composite unique constraint for (lesson_id, slide_number) to prevent duplicates
ALTER TABLE slides
ADD CONSTRAINT unique_lesson_slide_number UNIQUE (lesson_id, slide_number)
ON CONFLICT DO NOTHING;

-- Step 2: Ensure indexes are properly set up for performance
-- These are idempotent operations

CREATE INDEX IF NOT EXISTS idx_slides_lesson_id ON slides(lesson_id);
CREATE INDEX IF NOT EXISTS idx_slides_module_id ON slides(module_id);
CREATE INDEX IF NOT EXISTS idx_slides_course_id ON slides(course_id);
CREATE INDEX IF NOT EXISTS idx_slides_order ON slides(lesson_id, slide_number);
CREATE INDEX IF NOT EXISTS idx_slides_ai_generated ON slides(ai_generated);
CREATE INDEX IF NOT EXISTS idx_slides_created_at ON slides(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_slides_interaction_type ON slides(interaction_type);
CREATE INDEX IF NOT EXISTS idx_slides_approved_at ON slides(approved_at);

-- Step 3: Create or verify triggers for auto-updating timestamps
-- First, ensure the update_updated_at function exists
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if it exists to avoid conflicts
DROP TRIGGER IF EXISTS slides_updated_at ON slides;

-- Create the trigger
CREATE TRIGGER slides_updated_at
BEFORE UPDATE ON slides
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();

-- Step 4: Verify table structure (informational query, not altering)
-- This helps verify the migration was successful
-- Run after migration: SELECT column_name, data_type, is_nullable FROM information_schema.columns WHERE table_name = 'slides' ORDER BY ordinal_position;

-- Step 5: Add comments for documentation
COMMENT ON TABLE slides IS 'Presentation slides generated from lessons, with AI generation support';
COMMENT ON COLUMN slides.narration IS 'Speaker notes / presenter talking points for the slide';
COMMENT ON COLUMN slides.media_notes IS 'Recommendations for media, graphics, or videos to include';
COMMENT ON COLUMN slides.learning_objective IS 'SMART learning objective for this slide';
COMMENT ON COLUMN slides.interaction_type IS 'Type of learner interaction: quiz, video, interactive, discussion, reflection, image';
COMMENT ON COLUMN slides.ai_notes IS 'Additional notes from AI generation process';
COMMENT ON COLUMN slides.slide_type IS 'Slide purpose type: intro (hook), content (main), or conclusion (summary)';
COMMENT ON COLUMN slides.ai_generated IS 'Whether this slide was generated by AI (true) or manually created (false)';
COMMENT ON COLUMN slides.is_edited IS 'Whether the slide has been edited after initial generation';
COMMENT ON COLUMN slides.approved_at IS 'Timestamp when slide was approved by instructor';
COMMENT ON COLUMN slides.approved_by IS 'User ID of instructor who approved the slide';

COMMIT;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Run these after migration to verify everything is correct:

-- 1. Check slide table structure:
SELECT 
  column_name, 
  data_type, 
  is_nullable, 
  column_default
FROM information_schema.columns 
WHERE table_name = 'slides' 
ORDER BY ordinal_position;

-- 2. Check indexes:
SELECT 
  schemaname,
  tablename,
  indexname,
  indexdef
FROM pg_indexes 
WHERE tablename = 'slides'
ORDER BY indexname;

-- 3. Check triggers:
SELECT 
  trigger_name,
  event_object_table,
  event_manipulation
FROM information_schema.triggers 
WHERE event_object_table = 'slides';

-- 4. Check constraints:
SELECT 
  constraint_name,
  constraint_type,
  table_name
FROM information_schema.table_constraints 
WHERE table_name = 'slides'
ORDER BY constraint_type;

-- =====================================================
-- ROLLBACK SCRIPT (if needed)
-- =====================================================
-- If you need to rollback, you can:
-- 1. Drop added columns: ALTER TABLE slides DROP COLUMN slide_type CASCADE;
-- 2. Drop new indexes created
-- However, this migration only ADDS columns and doesn't remove anything, so it's safe
